kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-clds3s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clds3-app
  template:
    metadata:
      labels:
        app: clds3-app
    spec:
      containers:
        - name: node-clds3
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-nodejs-svc
spec:
ports:
  - name: http-3001
    port: 3000
    protocol: TCP
    targetPort: 3000
selector:
  app: clds3-app
